### ISSUE TITLE
Add resolution and accuracy to available location data

### ISSUE THREAD

**Issue by jkristin** [openxc/openxcplatform.com#12]
The Signal List (http://openxcplatform.com/vehicle-interface/output-format.html) states that Latitude / Longitude is available as whole degrees with one significant digit.

I have had the question whether our accuracy on the GPS is really 0.1 degrees ( = 11km for Lat and 9km for Lon in e.g. San Diego).

We should either change the example values (-89.0 to 89.0 => -89.00000 to +89.00000) or explicilty say that these are available as doubles (-89 to +89) with "standard GPS accuracy or better".

**Comment by sigkill** [comment]
Totally agree - do you comment in the google group as well? Chris seem's to be the man for feedback about this stuff.

--Bob

**Comment by jkristin** [comment]
No, Chris told me to post here ;)

**Comment by peplin** [comment]
Thanks for the report, I'll check on this - the accuracy is definitely greater than 11km! I like your second proposal of "standard GPS accuracy or better" so that's most likely what we'll end up using. This question also hits on the differences between what difference automakers may provide for different signals - e.g. Ford may provide higher accuracy with fuel consumption than someone else, but they have to use the same signal. I think when we have more than one automaker releasing binaries, the resolution will have to be specified individually.
