### ISSUE TITLE
Add new traces on the Platform Website

### ISSUE THREAD

**Issue by sudo-a13** [openxc/openxcplatform.com#72]
@peplin there was a need to add vehicle trace files collected in Delhi to the website. What is the best way to go about it?

**Comment by peplin** [comment]
The existing files are hosted in S3 account managed by Ford, so either upload them there or somewhere else and add a a link to https://github.com/openxc/openxcplatform.com/blob/gh-pages/resources/traces.mkd

**Comment by DaveMelcher** [comment]
Links and data in place, but getting Access Denied errors when I try to follow the link.  What aren't I setting up in the S3 Console?  I've given each file download/open permission for everyone.

**Comment by DaveMelcher** [comment]
Ok, it's working.  The new traces are all uncompressed.  Should we have Amazon gzip the new ones?

**Comment by peplin** [comment]
It really shrinks the files down quite a bit, so i'd definitely suggest it. The original reason was to make the trace-analyzer faster, since it has to download the trace every time you load the page and hold it in memory in your browser. The reason we had the warning is that the Android browser that everyone was using during OpenXC training in the emulator couldn't handle gzipped files - if you could check and see if that's still true, we can possibly get rid of the warning and just gzip everything by default.

**Comment by peplin** [comment]
Traces are up at http://openxcplatform.com/resources/traces.html, closing.
